### PR TITLE
Revised to match up with field_collection contrib

### PR DESCRIPTION
**Pull request by sherakama**
# Ready for review.
- Revised and removed all specific to JSE stuff.
- To test: pull down the latest courses (HSDO-293) and this module
- Enable and clear all caches
- Import stuff.
- Image import working.

Please use news_extras modules and the following feed for testing: https://engineering-apache.stanford.edu/news/xml

### CODE REVIEW

**Comment by tsui1** [comment]
:yum:

**Comment by sherakama** [comment]
Courses PR: https://github.com/SU-SWS/stanford_feeds_helper/pull/2

**Comment by boznik** [comment]
The mapping is preserved on jse but actually saving an image into a field collection is not working.
That is what sent me down the after save hook path route.

**Comment by sherakama** [comment]
@boznik,

Field collections and image functionality has been resolved. Please confirm.

**Comment by boznik** [comment]
Nice work @sherakama !!!

**Pull request merged**
